# Generated by Django 5.0.4 on 2024-08-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
    ]
