# Generated by Django 5.0.4 on 2024-08-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_season_options_remove_season_year_and_more'),
    ]

    operations = [
    ]
