# Generated by Django 5.0.4 on 2024-08-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_lineup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
    ]
