# Generated by Django 5.0.4 on 2024-08-03 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_options'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='current_championship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.championship', verbose_name='Current Championship'),
        ),
        migrations.AddField(
            model_name='club',
            name='current_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.league', verbose_name='Current League'),
        ),
        migrations.AddField(
            model_name='club',
            name='is_computer_managed',
            field=models.BooleanField(default=False, verbose_name='Computer Managed'),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
