# Generated by Django 5.0.4 on 2024-08-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_add_countries_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-number']},
        ),
        migrations.RemoveField(
            model_name='season',
            name='year',
        ),
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
