# Generated by Django 5.0.4 on 2024-08-05 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_season_options_remove_season_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='max_teams',
            field=models.PositiveIntegerField(default=18, help_text='The number of teams in this league. Fixed at 18.', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
